name: Update Major Tag
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  set-tag:
    if: github.repository_owner == 'jkroepke'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: 'false'

      - name: Push major tag
        #language=bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            TAG="${TAG%%.*}"
            git tag -f "${TAG}"
            git push --tags --force
          fi
